version: '3'
services:
  postgresql:
    image: postgres
    container_name: first
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=first
      - POSTGRES_PASSWORD=123
      - POSTGRES_DATABASE=first
    command: postgres
    restart: always
