export const users = [
  {
    _id: '63f8c595c89b08c719459462',
    index: 0,
    guid: '6f7438c9-7bab-437f-afac-39e7c816dfe4',
    isActive: false,
    balance: '$2,486.26',
    picture: 'http://placehold.it/32x32',
    age: 32,
    eyeColor: 'brown',
    name: 'Taylor Chapman',
    gender: 'male',
    company: 'ANDERSHUN',
    email: 'taylorchapman@andershun.com',
    phone: '+1 (892) 505-3329',
    address: '356 Pershing Loop, Avoca, Massachusetts, 9399',
    about:
      'Reprehenderit eiusmod duis amet ex id. Nulla eiusmod incididunt occaecat est tempor eiusmod sit anim nostrud ea aute ut. Amet reprehenderit Lorem dolor sunt excepteur et ad enim ipsum aute labore est non eiusmod. Excepteur aliquip nulla cupidatat minim reprehenderit consequat nisi. Nulla ad voluptate in tempor qui aute. Incididunt officia eiusmod cupidatat et duis incididunt ea non do Lorem. Occaecat culpa reprehenderit ut mollit laborum.\r\n',
    registered: '2015-08-27T12:24:48 -06:00',
    latitude: 7.547076,
    longitude: 41.019096,
    tags: ['qui', 'mollit', 'aliqua', 'enim', 'Lorem', 'proident', 'proident'],
    friends: [
      {
        id: 0,
        name: 'Paul Chandler',
      },
      {
        id: 1,
        name: 'Delaney Harper',
      },
      {
        id: 2,
        name: 'Parks Oliver',
      },
    ],
    greeting: 'Hello, Taylor Chapman! You have 6 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '63f8c595a1e77b955bba3335',
    index: 1,
    guid: '1540ade5-808b-4a79-ae7c-f280f8ab97b6',
    isActive: true,
    balance: '$2,581.18',
    picture: 'http://placehold.it/32x32',
    age: 37,
    eyeColor: 'blue',
    name: 'Ines Castillo',
    gender: 'female',
    company: 'MAZUDA',
    email: 'inescastillo@mazuda.com',
    phone: '+1 (882) 587-3027',
    address: '266 Bowery Street, Crucible, Montana, 5737',
    about:
      'Consectetur sit do irure irure tempor commodo adipisicing. Velit non esse ad aute veniam esse ut aliquip laborum ad. Est nulla est quis minim id tempor. Qui cillum dolore mollit ea est aliqua laboris officia et duis labore sint proident. Sint reprehenderit aliquip nulla labore ad id velit sint elit reprehenderit. Aliqua esse voluptate commodo ea in Lorem cupidatat culpa officia adipisicing.\r\n',
    registered: '2022-03-06T01:27:58 -06:00',
    latitude: -49.017374,
    longitude: 11.666508,
    tags: [
      'proident',
      'nostrud',
      'consequat',
      'consectetur',
      'id',
      'consectetur',
      'irure',
    ],
    friends: [
      {
        id: 0,
        name: 'Latisha Rich',
      },
      {
        id: 1,
        name: 'Helen Cote',
      },
      {
        id: 2,
        name: 'Sophie Greer',
      },
    ],
    greeting: 'Hello, Ines Castillo! You have 5 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '63f8c5956fefb17f1f656816',
    index: 2,
    guid: '7c90e854-d5ee-4ffa-b136-5b4254785161',
    isActive: true,
    balance: '$1,460.27',
    picture: 'http://placehold.it/32x32',
    age: 28,
    eyeColor: 'blue',
    name: 'Eloise Whitfield',
    gender: 'female',
    company: 'ACRODANCE',
    email: 'eloisewhitfield@acrodance.com',
    phone: '+1 (993) 438-3353',
    address: '352 Poly Place, Bangor, Louisiana, 1545',
    about:
      'Irure ea ea qui velit laboris velit enim est esse. Elit eu excepteur dolore nulla exercitation labore. Minim duis nostrud adipisicing veniam. Occaecat dolore eiusmod quis do. In proident aliquip eu veniam est consectetur minim.\r\n',
    registered: '2020-11-07T07:13:54 -06:00',
    latitude: -46.631832,
    longitude: -141.919689,
    tags: [
      'exercitation',
      'commodo',
      'voluptate',
      'cillum',
      'fugiat',
      'duis',
      'ex',
    ],
    friends: [
      {
        id: 0,
        name: 'Mccarty Mcfadden',
      },
      {
        id: 1,
        name: 'Britt Summers',
      },
      {
        id: 2,
        name: 'Georgette Wise',
      },
    ],
    greeting: 'Hello, Eloise Whitfield! You have 2 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '63f8c5957ec960c0a0405e3a',
    index: 3,
    guid: '52d1c6cb-142b-44d3-9da0-eeae76586d8f',
    isActive: false,
    balance: '$1,911.08',
    picture: 'http://placehold.it/32x32',
    age: 39,
    eyeColor: 'brown',
    name: 'Knight Kirk',
    gender: 'male',
    company: 'TECHMANIA',
    email: 'knightkirk@techmania.com',
    phone: '+1 (963) 483-2387',
    address: '343 Corbin Place, Cedarville, Nevada, 7898',
    about:
      'Non esse mollit est cupidatat cupidatat do dolore sint voluptate aliqua laborum cupidatat fugiat adipisicing. Fugiat et labore aliquip quis irure sit. Occaecat nisi tempor eiusmod consequat in. Occaecat tempor ipsum duis est. Non sunt laboris voluptate culpa irure. Irure ad laborum deserunt in. Ut sit consequat anim commodo non.\r\n',
    registered: '2019-02-15T03:41:54 -06:00',
    latitude: 53.666624,
    longitude: 85.272617,
    tags: [
      'in',
      'ullamco',
      'anim',
      'eiusmod',
      'cupidatat',
      'consequat',
      'sunt',
    ],
    friends: [
      {
        id: 0,
        name: 'Weiss Hays',
      },
      {
        id: 1,
        name: 'Margarita Talley',
      },
      {
        id: 2,
        name: 'Leola Blake',
      },
    ],
    greeting: 'Hello, Knight Kirk! You have 2 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '63f8c595d9b6945ea28f303c',
    index: 4,
    guid: 'd857d758-bda3-4319-933c-cda85e90a026',
    isActive: false,
    balance: '$1,669.01',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'brown',
    name: 'Maryanne Sanders',
    gender: 'female',
    company: 'FURNAFIX',
    email: 'maryannesanders@furnafix.com',
    phone: '+1 (926) 554-3765',
    address: '846 Martense Street, Jeff, District Of Columbia, 6216',
    about:
      'Aliquip do laborum labore labore dolore aute adipisicing ex officia amet pariatur. Consectetur deserunt sunt exercitation aliquip tempor tempor cupidatat. Magna sint ut nulla eiusmod in pariatur irure cillum qui aute voluptate. Est nisi officia deserunt eu aliquip in non aliquip id exercitation. Nisi incididunt voluptate magna in minim ullamco culpa ut in. Consectetur est sunt sit labore nostrud. Tempor sint in consequat aute ea aliqua commodo proident culpa incididunt eu.\r\n',
    registered: '2022-05-19T08:52:53 -06:00',
    latitude: -15.9172,
    longitude: -98.406571,
    tags: [
      'amet',
      'nulla',
      'cillum',
      'cupidatat',
      'proident',
      'cillum',
      'nostrud',
    ],
    friends: [
      {
        id: 0,
        name: 'Fisher Dawson',
      },
      {
        id: 1,
        name: 'Hutchinson Lowery',
      },
      {
        id: 2,
        name: 'Lynnette Lloyd',
      },
    ],
    greeting: 'Hello, Maryanne Sanders! You have 4 unread messages.',
    favoriteFruit: 'banana',
  },
];
